title: "Shock (Xiaoke) Jiang"
description: "Senior Researcher @ IDEA"
url: https://shockjiang.github.io
baseurl: ""

exclude:
  - old
  - docs
  - data
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - Dockerfile
  - docker-compose.yaml
  - CLAUDE.md
  - "*.py"
  - "*.ipynb"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
